export interface Transaction {
  amount: number;
  bonder: string;
  bondTransactionHash: string;
  bondTransactionHashTruncated: string;
  bondTxExplorerUrl: string;
  bonded: boolean;
  bonderFee: number;
  bonderTruncated: string;
  bonderUrl: string;
  destinationChain: number;
  destinationChainImageUrl: string;
  destinationChainName: string;
  destinationChainSlug: string;
  displayAmount: string;
  displayBonderFee: string;
  formattedAmount: number;
  index: number;
  isoTimestamp: string;
  relativeTimestamp: string | null;
  sourceChain: number;
  sourceChainImageUrl: string;
  sourceChainName: string;
  sourceChainSlug: string;
  sourceTxExplorerUrl: string;
  timestamp: number;
  token: string;
  tokenImageUrl: string;
  transactionHash: string;
  transactionHashTruncated: string;
  transferId: string;
  transferIdTruncated: string;
  bondedTimestamp: number;
  isoBondedTimestamp: string;
  relativeBondedTimestamp: string | null;
  relativeBondedWithinTimestamp: string | null;
}
